### ISSUE TITLE
One-Command Installation for platform dev environment

### ISSUE THREAD

**Issue by Ahmedr275** [marvelai-org/marvel-platform#174]
# Implementing a One-Command Installation Setup for Marvel AI Platform Development Environment

## Objective:

To streamline our local development setup for the Marvel AI platform, we are moving towards a single-command installation and startup process. This will make onboarding faster for new contributors and simplify workflow for existing team members. Our setup will leverage Docker and Docker Compose to encapsulate dependencies and provide live reloading, ensuring a productive development experience. Here’s how we’ll implement this.

## Overview of Changes

1. **Integrate AI Backend as a Git Submodule**
    
    We’ll add the ai-backend repository as a submodule within the platform repository. This will keep our repositories manageable and ensure that both the platform and AI backend are easy to clone and configure.
    
2. **Dockerize Each Component**
    
    We’ll create Docker configurations for each part of the application:
    
    - **Frontend (Next.js):** Run in development mode with hot reloading.
    - **Backend (Firebase Functions):** Use nodemon to reload on code changes.
    - **AI Backend (FastAPI):** Use uvicorn --reload to enable auto-reloading for Python.
3. **One-Command Setup with Docker Compose**
    
    A single docker-compose.yml file in the platform repository will define all services (frontend, backend, Firebase emulator, AI backend). This setup will allow contributors to start all services with a single command and immediately see changes they make to the codebase.
    

## Implementation Steps

1. **Submodule Integration**
    - Navigate to the platform repository.
    - Run:
        
        ```bash
        git submodule add <https://github.com/marvelai-org/marvel-ai-backend.git> ai-backend
        
        ```
        
    - Initialize and update the submodule:
        
        ```bash
        git submodule update --init --recursive
        
        ```
        
    - This will create an ai-backend directory inside the platform repository, linked to the AI backend code.
2. **Docker Configuration**
    - Create Dockerfiles for each service (frontend, backend, AI backend) to specify dependencies and configurations.
    - Set up each Dockerfile to include development tools (nodemon for backend, uvicorn --reload for AI backend, Next.js dev server) to enable live reloading.
    - Map the necessary volumes in Docker to sync local code changes directly into the containers.
3. **Compose Services with Docker Compose**
    - In the root of the platform repository, create a docker-compose.yml file with definitions for each service:
        - Frontend mapped to port 3000.
        - Backend (Firebase functions) mapped to port 5001.
        - Firebase Emulators for local development of authentication and database.
        - AI Backend mapped to port 8000.
    - Each service should use volume mapping to ensure live reloading and code synchronization without needing to rebuild containers.
4. **Streamline Environment Configuration**
    - Add `.env.example` files for both platform and ai-backend repositories, detailing necessary environment variables.
    - Update `.env` as needed, and ensure `.gitignore` includes `.env` to avoid committing sensitive information.
5. **Update Documentation for Contributors**
    - Update the README with the following simplified setup instructions:
    
    ```bash
    # Clone the platform repository with submodules
    git clone --recurse-submodules <https://github.com/radicalxdev/marvel-platform.git>
    cd marvel-platform
    
    # Start all services
    docker-compose up --build
    ```
    

**Expected Outcome**

This setup will provide a consistent development environment, ensuring contributors can:

- Clone both the platform and ai-backend repositories with a single command.
- Start all services with `docker-compose up --build.`
- Edit code in real-time with live reloading for frontend, backend, and AI backend services.

This single-command setup will enhance productivity, reduce setup times, and make our platform more accessible for open-source contributions. Let’s collaborate to finalize this implementation and test the configuration.

**Comment by yunusj** [comment]
Completed and Merged in PR #181 ⚡️
